language: node_js
node_js:
  - "8"
addons:
  chrome: stable
before_script:
  - npm install -g @angular/cli@13.0.3
  - npm install
script:
  - npm run test-lib
after_success:
  - ./node_modules/.bin/codecov -f test-output/angular-mydatepicker/coverage-final.lcov
sudo: required
